Workaround so camcrypt can be imported on Python3.
This should probably be fixed upstream, but the library explicitly
allows the caller to supply the path, so we might as well do that.

Before:

    >>> import camcrypt
    >>> camcrypt.CamCrypt()
    OSError: .../camcrypt/camellia.so: No such file or directory

And:

    Ran 75 tests in 0.412s

After:

    Ran 131 tests in 0.503s